### ISSUE TITLE
Class 'XoopsModules/Countdown2/Helper' not found

### ISSUE THREAD

**Issue by liomj** [mambax7/countdown2#9] opened 2020-05-20 08:39 UTC
Errors in index.php after updating the module in admin 
--
Error: Error: Class 'XoopsModules/Countdown2/Helper' not found in file /modules/countdown2/header.php line 37

**Comment by mambax7** [comment] 2020-05-21 02:51
I can't reproduce it. Can you check if it still there after you've renamed it to "Countdown"?

**Comment by liomj** [comment] 2020-05-21 04:01
yes it is still there

1. open up two browser tabs
2. first tab is front page with countdown block activated
3. 2nd tab is xoops admin
4. go to module admin- update countdown
5. refresh first tab and you received the error same in index.php
6. after second refresh the error message is gone

**index.php**
Error: Error: Class 'XoopsModules/Countdown/Helper' not found in file /modules/countdown/header.php line 37


**front page**
Errors
--
Error: Error: Class 'XoopsModules/Countdown/Helper' not found in file /modules/countdown/blocks/countdown-block.php line 7

**Comment by mambax7** [comment] 2020-05-21 04:23
You need to clean the cache or reinstall the module, because after you renamed it to "Countdown", there should be no message like this:

`not found in file /modules/countdown2/header.php line 37`

because there should be no module "countdown2"

**Comment by mambax7** [comment] 2020-05-21 04:30
However, try to use this code in "modules/countdown/header.php" and see if it helps:

```
use Xmf\Request;
use XoopsModules\Countdown;
use XoopsModules\Countdown\Helper;
use XoopsModules\Countdown\Common;

include __DIR__ . '/preloads/autoloader.php';

require dirname(dirname(__DIR__)) . '/mainfile.php';
require XOOPS_ROOT_PATH . '/header.php';

$moduleDirName = basename(__DIR__);

$helper       = Helper::getInstance();
$utility      = new Countdown\Utility();
$configurator = new Common\Configurator();
$copyright    = $configurator->modCopyright;

$modulePath = XOOPS_ROOT_PATH . '/modules/' . $moduleDirName;
require_once __DIR__ . '/include/common.php';
$db = \XoopsDatabaseFactory::getDatabaseConnection();

$myts = \MyTextSanitizer::getInstance();

if (!isset($GLOBALS['xoTheme']) || !is_object($GLOBALS['xoTheme'])) {
    require $GLOBALS['xoops']->path('class/theme.php');
    $GLOBALS['xoTheme'] = new xos_opal_Theme();
}

$stylesheet = "modules/{$moduleDirName}/assets/css/style.css";
if (file_exists($GLOBALS['xoops']->path($stylesheet))) {
    $GLOBALS['xoTheme']->addStylesheet($GLOBALS['xoops']->url("www/{$stylesheet}"));
}
/** @var \XoopsPersistableObjectHandler $eventsHandler */
$eventsHandler   = new Countdown\EventsHandler($db);
$categoryHandler = new Countdown\CategoryHandler($db);

// Load language files
$helper->loadLanguage('main');
$helper->loadLanguage('modinfo');
```

**Comment by liomj** [comment] 2020-05-21 04:45
> You need to clean the cache or reinstall the module, because after you renamed it to "Countdown", there should be no message like this:
> 
> `not found in file /modules/countdown2/header.php line 37`
> 
> because there should be no module "countdown2"

i copy paste the error in the first post

**Comment by liomj** [comment] 2020-05-21 04:48
> However, try to use this code in "modules/countdown/header.php" and see if it helps:
> 
> ```
> use Xmf\Request;
> use XoopsModules\Countdown;
> use XoopsModules\Countdown\Helper;
> use XoopsModules\Countdown\Common;
> 
> include __DIR__ . '/preloads/autoloader.php';
> 
> require dirname(dirname(__DIR__)) . '/mainfile.php';
> require XOOPS_ROOT_PATH . '/header.php';
> 
> $moduleDirName = basename(__DIR__);
> 
> $helper       = Helper::getInstance();
> $utility      = new Countdown\Utility();
> $configurator = new Common\Configurator();
> $copyright    = $configurator->modCopyright;
> 
> $modulePath = XOOPS_ROOT_PATH . '/modules/' . $moduleDirName;
> require_once __DIR__ . '/include/common.php';
> $db = \XoopsDatabaseFactory::getDatabaseConnection();
> 
> $myts = \MyTextSanitizer::getInstance();
> 
> if (!isset($GLOBALS['xoTheme']) || !is_object($GLOBALS['xoTheme'])) {
>     require $GLOBALS['xoops']->path('class/theme.php');
>     $GLOBALS['xoTheme'] = new xos_opal_Theme();
> }
> 
> $stylesheet = "modules/{$moduleDirName}/assets/css/style.css";
> if (file_exists($GLOBALS['xoops']->path($stylesheet))) {
>     $GLOBALS['xoTheme']->addStylesheet($GLOBALS['xoops']->url("www/{$stylesheet}"));
> }
> /** @var \XoopsPersistableObjectHandler $eventsHandler */
> $eventsHandler   = new Countdown\EventsHandler($db);
> $categoryHandler = new Countdown\CategoryHandler($db);
> 
> // Load language files
> $helper->loadLanguage('main');
> $helper->loadLanguage('modinfo');
> ```

yes this fix the problem in the countdown index and event page

**Comment by mambax7** [comment] 2020-05-21 04:59
Can you close it then? 
Thanks!

**Comment by liomj** [comment] 2020-05-21 05:46
The error in block still exists

Error: Error: Class 'XoopsModules/Countdown/Helper' not found in file /modules/countdown/blocks/countdown-block.php line 7

**Closed as completed** 2020-05-21 08:49 UTC
Labels: bug

**Comment by liomj** [comment] 2020-05-21 08:51
Mamba in countdown-block.php fix     there are two $block = [];
is this intentional ?

**Comment by mambax7** [comment] 2020-05-21 09:05
My bad, sorry! You can remove one of them.
